language:
- c
- cpp

# clang is not supported for poppler
compiler: gcc

cache:
- ccache

os: linux
dist: xenial

sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gbpO001CnG6qPdcDr3t9SYL/C9DnxJZBeaAt+jKrd7SJ3Db0cKfVJRs9BTVrpznuoMNpb3T8R6gludUGNgxn2OkASHrlPBoK6xp4Npo4LVfbA6LVQsXr7znQnBueOQ//5WUhYoKGrbaeuxGAAcCxVNnCwmwp+nACPMobYUcGvlXc0Qx3Ao1PTKnk0lYCnkWlHxBcSZoUDjOCmanEvavNxapq29bnouO6EWEpu1tp0UngG0rA6irMOcSMmg7GtxJpk0uJ4JQm0GHWI2swU5VptKdS3cJ1o04+l9sfvElv2ekgNKlp1tqsJJpzg6VHwtt5kOkfzD8MfV0CY6084LEGAKz92uIHFdDI9jOlGJ0idjQyumWV59yVXw0a6visBzHzwEKxh4OgMS2GIdIfkzD1ipDz0Oq6bPaW6ueJ8fkQIaenwGqSiCyyfA9ULyqz/erSrV6rYBtBcgmer661RmVeEfZoa6O5TETEzRIMowJnOuU9PTrkoPmsSyfTXloeWpD3gkk7+2W7mLm/HXlKV1NJnT3fnq3lmgEmd2yoGB49aWTa3cf0xa0lnXlHqXAAmdvduebKN10byf3wcaDkb5ZzcF7iWYqYtUgiWGDX2lnN7kSFtjfF2+MkpfDQrKQyzxeIIzyjxFQ05ooZwcTW0R6X3EKGtwH8nUxSoMIsVUEGpGM="

addons:
  apt:
    packages:
    - cmake

    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-locale-dev
    - libboost-iostreams-dev
    - libcppunit-dev

#    - dvipng
    - texlive
#    - liblcms2-dev
#    - fontconfig
    - libgtk-3-dev
    - libpoppler-glib-dev

# Do not use PPAs, use standard Ubuntu Sources
#    sources:
#    - boost-latest
#    - kalakris-cmake

  coverity_scan:
    project:
      name: "xournalpp/xournalpp"
      description: "Notetaking software designed around a tablet."
    notification_email: peter_klausing@wh2.tu-dresden.de
    build_command_prepend: "cmake .. -DBUILD_POPPLER=ON -DENABLE_MATHTEX=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON"
    build_command: "make"
    branch_pattern: coverity_scan

before_script:
  - "mkdir build"
  - "cd build"

script:
  - "cmake .. -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DENABLE_MATHTEX=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON -DDEBUG_COMPILE=ON"
  - "make"
  - "ctest"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4879506130dac18d2f63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

