language:
- c
- cpp

# clang is not supported for poppler
compiler: gcc

os: linux

sudo: false

cache:
- ccache

env:
  global: 
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DxwzqXcJV/9qPwUCi7DQrqzeU73ACRhS0i8suV9tYpUDJ7ZuwwSK/GMVt2jMTNjZbJwKFv8ELLu0MIdTfX3UvG+++lfxLx4yldEwl4CtjPJaClB2rTou2SAiZPMBMyX6eHKfx0XB4xtsqwtKRIvF47tB9i3w+aPcb8C4DE6hXmU="


addons:
  apt:
    packages:
    - cmake
    - libboost1.55-all-dev
    - libcppunit-dev
    - dvipng
    - texlive
    - liboverlay-scrollbar-0.2-dev
    - liblcms2-dev
    - libopenjpeg-dev
    - libjpeg-dev
    - fontconfig
    - librsvg2-dev
    - glade-gtk2
    - libglade2-dev
#    - libpoppler-dev
#    - libpoppler-cpp-dev
#    - libpoppler-glib-dev
    sources:
    - boost-latest
    - kalakris-cmake
  coverity_scan:
    project:
      name: "MarPiRK/xournalpp"
      description: "Notetaking software designed around a tablet."
    notification_email: marek@pikula.co
    build_command_prepend: "mkdir build && cd build && cmake .. -DBUILD_POPPLER=ON -DEXT_GLIBMM=ON -DENABLE_MATHTEX=ON -DENABLE_OS=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON"
    build_command: "make"
    branch_pattern: coverity_scan

before_script:
  - "mkdir build"
  - "cd build"

script:
  - "cmake .. -DBUILD_POPPLER=ON -DEXT_GLIBMM=ON -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DENABLE_MATHTEX=ON -DENABLE_OS=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON -DDEBUG_COMPILE=ON"
  - "make"
  - "ctest"

notifications:
  slack: xournalpp:D5mvotdm0Rnn0ejvZf0FIxgV
