# Template for building Xournal++ on Linux

parameters:
  build_type: 'Debug'
  cmake_flags: ''

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y cmake ninja-build libcppunit-dev libgtk-3-dev libpoppler-glib-dev portaudio19-dev libsndfile-dev liblua5.3-dev libzip-dev
    displayName: 'Install dependencies'
  - bash: |
      mkdir build
    displayName: 'Create build directory'
  - bash: |
      cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type}} ${{ parameters.cmake_flags }}
      cmake --build .
    workingDirectory: ./build
    displayName: 'Build Xournal++'