# Template for setting up the Ubuntu build environment and building Xournal++ on
# Ubuntu

parameters:
  build_type: 'Debug'
  gcc_version: '8'

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y librsvg2-dev gcc-${{ parameters.gcc_version }} g++-${{ parameters.gcc_version }} cmake ninja-build \
        libgtk-3-dev libpoppler-glib-dev portaudio19-dev libsndfile-dev \
        liblua5.3-dev libzip-dev gettext help2man libgtest-dev
      g++ --version
    displayName: 'Install dependencies'
